### PR TITLE
Typos and sentences fixed in contribution guide

### PR DESCRIPTION
**Pull request by SenseException**
I did some minor fixes of typos and a few changes of sentences. Nothing big, since the contribution guide is already a good starter and will grow over time.

I've added the PHP Coding Standards Fixer to the tools, since this may be useful for some developers.

### CODE REVIEW

**Comment by eps90** [comment]
Thanks, those were really unwanted. Maybe because the whole document was made during one night and I made some typos. Let me read this once again and I think it can be merged soon.

**Comment by SenseException** [comment]
Sounds familiar to me :-)

**Comment by eps90** [comment]
It's called overworked developer syndrome ;) Merging!

**Comment by eps90** [comment]
And thanks for your support :)

**Comment by andres-montanez** [comment]
Thanks everyone! :)

**Pull request merged**
