### PR TITLE
Fix/rollback release directory

### PR DESCRIPTION
**Pull request by jhuet**
Rollback directory should include `deployment:to` config variable as it's done in [release task](https://github.com/andres-montanez/Magallanes/blob/master/Mage/Task/BuiltIn/Deployment/ReleaseTask.php#L44-L46).

### CODE REVIEW

**Comment by eps90** [comment]
Does anyone tested it ?:) @jhuet ?

**Comment by jhuet** [comment]
@eps90, i've been using this for some time now and it's working but i havent written unit test if that's the question ;)

**Comment by eps90** [comment]
Well, if it's not the problem, for sure it's gonna be the big advantage for the project :) But in the other hand it's hard to test classes extending non-tested other one. The final decision is yours :)

**Comment by jhuet** [comment]
Alright, you can merge it.

**Comment by eps90** [comment]
Ok, merging! Thanks for contribution! :)

**Comment by andres-montanez** [comment]
Many thanks!

**Pull request merged**
