### PR TITLE
security fix, use escapeshellcmd()

### PR DESCRIPTION
**Pull request by drAlberT**

### CODE REVIEW

**Comment by eps90** [comment]
Great! Thanks a lot! :)

**Comment by drAlberT** [comment]
@eps90 I can confirm that applying this PR without updating commands to properly make escapes **breaks** the commands execution .. 

So you should revert or test that everything works as expected ..

**Comment by eps90** [comment]
@drAlberT Could you create a new issue with link to this issue? I'll test it in my free time and such issue will be better to find.

**Comment by drAlberT** [comment]
@eps90 Ok .. it could suffice to simply escape the command, without the output redirection .. but only id for "command" we intend the program name .. otherwise the command line has to be difided into command name + arguments (being escaped by escape_shell_args ) ..

**Comment by drAlberT** [comment]
New issue opened as requested #237

**Pull request merged**
