### PR TITLE
Added php-cs-fixer integration and config file

### PR DESCRIPTION
**Pull request by drAlberT**

### CODE REVIEW

**Comment by eps90** [comment]
You've committed a `composer.json` but I can't see any `composer.lock`

**Comment by drAlberT** [comment]
@eps90 you are right, my bad I forgot it .. I'll upload next week .. I'm on vacation now :)

**Comment by drAlberT** [comment]
@eps90 done, but I don't understand why coverage is decreased ...

**Comment by drAlberT** [comment]
@eps90 any news?

**Pull request closed without merging**
