### PR TITLE
Ignoring errors while deleting temp files

### PR DESCRIPTION
**Pull request by d-ulyanov**
Release should not fail if temp files not found

### CODE REVIEW

**Comment by eps90** [comment]
What kind of errors were there?

**Comment by eps90** [comment]
Okay, when I saw the PR, I was just-after wake up :) Sorry about the question above. 
Seems good, checking if file exist would only increase the complexity. So for me it's ok.

**Comment by d-ulyanov** [comment]
Ok, could you merge it? :)

**Comment by d-ulyanov** [comment]
We don't need to check that tmp file exists - just delete.

**Comment by eps90** [comment]
I'll test that first (which seems to be ok) and then merge :) I'll do it ASAP.

**Comment by eps90** [comment]
Seems everything is OK ;) I hadn't noticed any errors. Thanks a lot for this contribution! Merging! :)

**Comment by andres-montanez** [comment]
Thanks everyone!!

**Pull request merged**
