### PR TITLE
added $currentCopy to the RollbackTask.php

### PR DESCRIPTION
**Pull request by ZesInternational**
A revision of the fix for issue #206

### CODE REVIEW

**Comment by ZesInternational** [comment]
@eps90 here is the PR in develop and with the rtrim included

**Comment by eps90** [comment]
Great, can we close the other one then? This commit would be in develop stage and will be merged into master with the nearest release.

**Comment by ZesInternational** [comment]
Yes, we can close the issue

**Comment by eps90** [comment]
Ok so since this PR is "more correct" than the other one, I'll reopen this one and close the other.

**Pull request merged**
