### PR TITLE
Feature/task permissions

### PR DESCRIPTION
**Pull request by jhuet**
Adds the `filesystem\permissions` task to allow change of permissions on given paths. Change will be done on local or remote host depending on the stage of the deployment. Usage could be :

```yaml
   on-deploy:
     - filesystem/permissions:
         paths:
             - /var/www/myapp/app/cache
             - /var/www/myapp/app/logs
         recursive: false
         checkPathsExist: true
         owner: www-data:www-data
         rights: 775
```

Also adds the task `filesystem\permissions-writable-by-web-server` wich extends `filesystem\permissions` with default values in order to give web server user rights to write on given paths. Usage could be :

```yaml
   on-deploy:
     - filesystem/permissions-writable-by-web-server:
         paths:
             - /var/www/myapp/app/cache
             - /var/www/myapp/app/logs
         recursive: false
         checkPathsExist: true
```

Finally, i added a last task `filesystem/permissions-readable-only-by-web-server` that also extends `filesystem\permissions` but this time in order to give only to web server user read permissions on given paths. Usage could be : 

```yaml
   on-deploy:
     - filesystem/permissions-readable-only-by-web-server:
         paths:
             - /var/www/myapp/app/config/config.yml
             - /var/www/myapp/app/config/parameters.yml
         recursive: false
         checkPathsExist: true
```

### CODE REVIEW

**Comment by andres-montanez** [comment]
Hi everyone!
Many thanks for the feedback and the development on the discussion.
To be true, I'm not familiar with the ````acl````, so @jhuet lets go with the classic implementation, let me know if it is done already, and aim for future improvements towards the ````acl```` approach.

Thanks again!

**Comment by jhuet** [comment]
Hi @andres-montanez thanks for the feedback. For now the PR is ok to merge IMHO, i've been using it for a few weeks now.

**Comment by eps90** [comment]
For me it's also ok :+1:

**Comment by andres-montanez** [comment]
Thank you, everyone!

**Pull request merged**
